<template>
  <div class="_help-page">
    <div class="_help-title">ngenCERF Calibration Workflow - Results Tab</div>
    <div class="_help-subtitle">This tab provides the user the ability to review the final plots generated by ngen-cal.
      The user can select the Evaluate button to view time-series data generated during the calibration run.</div>

    <table class="_help-table">
      <tbody>
        <tr>
          <td class="td1">EVALUATE Button:</td>
          <td class="td2">Go to the Evaluation Workflow Evaluate tab. (Under Construction)</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup lang="ts">

</script>

<style lang="scss" scoped>
@import "@/assets/styles/styles.scss";
</style>
