<template>
  <div class="_help-page">
    <div class="_help-title">ngenCERF Calibration Workflow - Results Tab</div>
    <div class="_help-subtitle">This tab provides the user the ability to review the final plots generated by ngen-cal.
    </div>
    <p class="text-center" style="color:#cc5500;font-size:0.8em;">
      WARNING: Clicking the browser refresh button takes you to the Calibration Runs tab.
    </p>

    <table class="_help-table">
      <thead>
        <tr>
          <th>Item</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="td1">Display:</td>
          <td class="td2">Once at least one iteration has been completed, plots are available for monitoring the calibration 
            process. Use this pulldown to select the plot. A message will appear if the plot is not available yet. </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup lang="ts">

</script>

<style lang="scss" scoped>
@use "@/assets/styles/global.scss";
@use "@/assets/styles/styles.scss";
</style>
