name: ngencerf-ui

services:
  ngencerf-app:
    image: ghcr.io/ngwpc/ngencerf-ui:${NGENCERF_UI_TAG:-latest}
    pull_policy: build
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000

