name: ngencerf-ui

services:
  ngencerf-app:
    extends:
      file: compose.yaml
      service: ngencerf-app
    image: registry.sh.nextgenwaterprediction.com/ngwpc/nwm-ngen/nextgen_ui:prod
    pull_policy: always
    build: 
      dockerfile: ./Dockerfile.production-pw

