name: ngencerf-ui

services:
  ngencerf-app:
    extends:
      file: compose.yaml
      service: ngencerf-app
    image: ghcr.io/ngwpc/ngencerf-ui:prod
    pull_policy: always
    build:
      dockerfile: ./Dockerfile.production-pw

